### ISSUE TITLE
[QUESTION] question title

### ISSUE THREAD

**Issue by wd904396578** [apache/incubator-dolphinscheduler#2881] opened 2020-06-03 03:14 UTC
http节点超时时间的配置在哪里设置，没有找到啊？？？

**Comment by wd904396578** [comment] 2020-06-03 03:21
http 节点，提供出参数设置的文件了吗

**Comment by dailidong** [comment] 2020-06-03 03:28
I see the HttpTask source code， the timeout is 60000 by default
`protected static final int MAX_CONNECTION_MILLISECONDS = 60000;`

if you're interesting in this , you can implement it

By the way, please update or add title and desc in English, thx

**Comment by dailidong** [comment] 2020-06-03 16:35
Duplicate of #2882

**Closed by dailidong** 2020-06-03 16:35 UTC
Labels: question
