### ISSUE TITLE
process instance stop cannot support all the of task type 

### ISSUE THREAD

**Issue by jiakai908** [apache/incubator-dolphinscheduler#2670] opened 2020-05-11 04:30 UTC
when we stop the process instance,case when task type is SQLTask. this way is not access.

**Comment by break60** [comment] 2020-05-11 09:25
Are you a process instance stopped, sql task is not accessible or does not support other task types?
Can you describe it in detail

**Comment by xingchun-chen** [comment] 2020-06-18 07:33
I don't understand what the problem is, can you describe it in detail

**Comment by break60** [comment] 2020-06-18 10:15
https://jingyan.baidu.com/article/870c6fc3466434b03fe4beea.html

**Comment by gabrywu** [comment] 2020-06-21 08:39
@jiakai908 Is your problem resolved? If you don't reply for a long time, I will close this issue firstly

**Closed by gabrywu** 2020-06-21 08:39 UTC
Labels: wontfix
