### ISSUE TITLE
cannot check condition [beforeDrop]Error: Syntax error, unrecognized expression: #function(t){return this.filter((function(e){return t.indexOf(e)<0}))}

### ISSUE THREAD

**Issue by weiyuanyong** [apache/incubator-dolphinscheduler#3172] opened 2020-07-09 10:26 UTC
this is js error log:cannot check condition [beforeDrop]Error: Syntax error, unrecognized expression: #function(t){return this.filter((function(e){return t.indexOf(e)<0}))}.

dolphinscheduler version:1.3.1-release

操作流程：进入工作流编辑页面（即http://ip:8888/#/projects/definition/list/127），当给两个节点建立连接时，鼠标放开，则报上述js错误。
经自己排查，定位到代码处：dag.js中JSP.handleEvent()处 -》 jsPlumbHandle.js中this.JspInstance.bind('beforeDrop', function (info) 处 -》 jsplumb.js中this.checkCondition函数处 抛出异常。

此错误导致的后果是，工作流节点前后关系(preTask)无法保存。请问如何修复此问题，感谢！
附上图片：
![scheduler-1](https://user-images.githubusercontent.com/3657319/87028732-a4014280-c211-11ea-9453-d11208819ff6.png)
![scheduler-2](https://user-images.githubusercontent.com/3657319/87028741-a794c980-c211-11ea-96b3-4cc2cac7602e.png)
<img width="1193" alt="scheduler-3" src="https://user-images.githubusercontent.com/3657319/87028744-a95e8d00-c211-11ea-843f-07925421e41e.png">

**Comment by yangyichao-mango** [comment] 2020-07-24 02:19
Hi,

I do not reproduce this bug in `1.3.1-release` branch, please describe more detail about how to reproduce this bug.
If you have any question or suggestion, welcome to put forward.

**Comment by chengshiwen** [comment] 2021-04-10 10:46
Close this issue since it can't be reproduced

**Closed by chengshiwen** 2021-04-10 10:46 UTC
