### ISSUE TITLE
[BUG] jobs with "kill" status will not be execute when recovery failed

### ISSUE THREAD

**Issue by kuky1201** [apache/incubator-dolphinscheduler#2686] opened 2020-05-12 05:31 UTC
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
Job A have a sub job B in it.
When I  run the job A at first time, a node "mytask" In job B has not any responses,so I killed the process on server by using "kill -9 ###".Then "mytask" was changed it's status to "kill".
I stopped the Job A and recovery failed and then I get into the instance job B ,I found "my task" was not runing and was still with status "kill",but at that moment the status of job B is success and the job A was go on running.

我有一个”任务A“，里面有一个子任务”任务B“。
当我第一次运行任务A时，在子任务B中有个名为"mytask"的节点执行没有反应，于是我在服务器上使用kill -9 ###命令将其执行的进程杀掉了。此时"mytask"节点的状态被自动变为kill。于是我停止了任务A的运行，开始执行恢复错误，这时我进到任务B中查看mytask，状态还是kill，但任务B的状态居然变成了success，然后任务A认为任务B成功了，继续往后执行

**Comment by dailidong** [comment] 2020-05-15 15:45
which version?

**Comment by xingchun-chen** [comment] 2020-06-18 07:08
The problem is the same as #2634，The issue has been resolved in dev_1.3.0

**Closed by xingchun-chen** 2020-06-18 07:08 UTC
Labels: bug
