### ISSUE TITLE
  Why does the HSQL task on the sql node report an error?

### ISSUE THREAD

**Issue by shiliquan** [apache/incubator-dolphinscheduler#4426] opened 2021-01-12 03:52 UTC
When the HIVE job starts in sql, it's not with the tenant's own ticket? Lt This user is a user I granted the DS itself, only read and write access to hdfs. When I created the source hive with other tenants and referenced the HSQL task in the run sql task, the following error occurred:
![image](https://user-images.githubusercontent.com/42087586/104267107-f165b180-54cb-11eb-9d5c-db5cb642f0d9.png)

**Comment by xingchun-chen** [comment] 2021-02-22 02:35
the issue is the same as #4450 , so I will close this issue

**Closed by xingchun-chen** 2021-02-22 02:35 UTC
Labels: question
