### ISSUE TITLE
运行 sparkr任务 connect to server 0.0.0.0/0.0.0.0:8032

### ISSUE THREAD

**Issue by yangqiangqiang1** [apache/incubator-dolphinscheduler#2348] opened 2020-04-01 01:20 UTC
*For better global communication, please give priority to using English description, thx! *

**Describe the question**
A clear and concise description of what the question is.

**Which version of DolphinScheduler:**
 -[1.1.0-preview]

**Additional context**

**Requirement or improvement
- Please describe about your requirements or improvement suggestions.

**Comment by yangqiangqiang1** [comment] 2020-04-01 01:31
运行spark组件   会一直报  尝试 connect to server 0.0.0.0/0.0.0.0:8032 。尝试很多次后任务结束，无法正常运行spark任务。 命令在  shell 中 spark-submit 可以正常运行

**Comment by yangqiangqiang1** [comment] 2020-04-01 03:04
问题解决了，  spark 里面没有yarn-site.xml  和 core-site.xml配置文件。 在本地执行spark-submit不会影响。

**Comment by dailidong** [comment] 2020-04-01 03:06
could you add English description to help more people , thx

**Comment by dailidong** [comment] 2020-04-01 03:07
glad to hear that you have solved this problem, good job

**Comment by xingchun-chen** [comment] 2020-04-01 06:53
The problem is resolved, please remember to close the issue

**Closed** 2020-04-01 14:05 UTC
Labels: question
