### ISSUE TITLE
on one note, the sql will change by itselt as same the last or next sql

### ISSUE THREAD

**Issue by datahao** [apache/incubator-dolphinscheduler#2992] opened 2020-06-16 06:54 UTC
在一个流里面又好多个sql，点开一个节点出现这样的问题，就是该节点每次点开sql会出现上个节点或者下个节点的sql，每次打开都可能会变

**Comment by xingchun-chen** [comment] 2020-06-16 07:02
The problem is the same as #2515, it has been resolved in dev_1.3.0 
Please update the title in English, thanks!

**Closed** 2020-06-16 07:32 UTC
