### ISSUE TITLE
[Bug][Resource] After uploading a shell script file, only one node exists the file.

### ISSUE THREAD

**Issue by wssmao** [apache/incubator-dolphinscheduler#4577] opened 2021-01-26 10:39 UTC
**Describe the bug**
After uploading a shell script file, only one node exists the file.

**To Reproduce**
Steps to reproduce the behavior, for example:
1. Upload a shell script file on a DS Cluster which include two nodes.
2. Only one node exists the file.

**Which version of Dolphin Scheduler:**
 -[1.3.4-release]

**Comment by xingchun-chen** [comment] 2021-01-27 02:26
I don't know what you mean. Can you take a screenshot

**Comment by chengshiwen** [comment] 2021-04-10 09:03
Close this issue since it can't be reproduced due to no updates for long time

**Closed by chengshiwen** 2021-04-10 09:03 UTC
Labels: bug
