### ISSUE TITLE
Sparksql has failed to run, indicating that the database does not exist.(sparksql一直运行失败，提示数据库不存在。)

### ISSUE THREAD

**Issue by fanguanqun** [apache/incubator-dolphinscheduler#246] opened 2019-05-05 02:27 UTC
Sparksql has failed to run, indicating that the database does not exist. When the interface tests the spark data source in the data source center, the test is successful. After the sparksql node is restored to normal.

---
sparksql一直运行失败，提示数据库不存在。当界面在数据源中心对spark数据源测试时，显示测试成功。之后sparksql节点又恢复了正常。

**Comment by lidongdai** [comment] 2019-05-06 02:25
Please do not close the issue. When the problem is discovered next time, please submit it manually. If the submission is working normally, please tell us. thx!

Stay concerned

**Closed** 2020-03-17 08:11 UTC
Labels: need more information
