### ISSUE TITLE
[BUG] fix "wait(...)" should be used instead of "Thread.sleep(...)" when a lock is held

### ISSUE THREAD

**Issue by Jave-Chen** [apache/incubator-dolphinscheduler#1648] opened 2019-12-30 13:53 UTC
*For better global communication, please give priority to using English description, thx! *

**Describe the bug**
If Thread.sleep(...) is called when the current thread holds a lock, it could lead to performance and scalability issues, or even worse to deadlocks because the execution of the thread holding the lock is frozen. It's better to call wait(...) on the monitor object to temporarily release the lock and allow other threads to run.

see sonarcloud : https://sonarcloud.io/project/issues?id=apache-dolphinscheduler&issues=AW9PvkGGYzPBRjkobY32&open=AW9PvkGGYzPBRjkobY32

**Comment by xingchun-chen** [comment] 2020-03-31 01:33
If the issue is resolved, please close it

**Closed** 2020-07-14 09:01 UTC
Labels: bug
