### ISSUE TITLE
创建租户失败后台报错

### ISSUE THREAD

**Issue by JunjianS** [apache/incubator-dolphinscheduler#2391] opened 2020-04-10 02:52 UTC
dolphinscheduler 1.2.0

configure hdfs（kerberos authentication），but fail to create tenamt，below is error message 

`[ERROR] 2020-04-10 10:08:26.360 org.apache.dolphinscheduler.api.controller.TenantController:[86] - create tenant error
java.io.IOException: Failed on local exception: java.io.IOException: org.apache.hadoop.security.AccessControlException: Client cannot authenticate via:[TOKEN, KERBEROS]; Host Details : local host is: "xxxxx/172.xx.xx.xx"; destination host is: "hadoopxx":8020; 
	at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:776)
	at org.apache.hadoop.ipc.Client.call(Client.java:1479)
	at org.apache.hadoop.ipc.Client.call(Client.java:1412)
	at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:229)
	at com.sun.proxy.$Proxy149.mkdirs(Unknown Source)
	at org.apache.hadoop.hdfs.protocolPB.ClientNamenodeProtocolTranslatorPB.mkdirs(ClientNamenodeProtocolTranslatorPB.java:558)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
`

**Comment by yh2388** [comment] 2020-04-10 02:57
you can refer to #2223

**Comment by JunjianS** [comment] 2020-04-10 06:51
> you can refer to #2223

thanks，it works,  why ?

**Comment by dailidong** [comment] 2020-04-11 00:43
please update/add title/desc in English,thx

**Comment by dailidong** [comment] 2020-04-12 02:59
Duplicate of #2223

**Closed by dailidong** 2020-04-12 02:59 UTC
Labels: question
