### ISSUE TITLE
[Improvement][worker] When running the node alone, the worker group didn't support choose. 

### ISSUE THREAD

**Issue by wssmao** [apache/incubator-dolphinscheduler#4580] opened 2021-01-27 01:10 UTC
**Describe the question**
When running the node alone, the worker group didn't support choose. 
![image](https://user-images.githubusercontent.com/39487209/105927238-92349f00-607e-11eb-8550-ed7d830d9138.png)

Sometimes only a node must choose the worker group,  such as the node have more cpu or memory.

**Which version of DolphinScheduler:**
 -[1.3.4-release]

**Describe alternatives you've considered**

**Comment by xingchun-chen** [comment] 2021-01-27 02:08
I think it can be optimized. Is anyone willing to do it

**Comment by chengshiwen** [comment] 2021-04-02 11:26
@wssmao You can try the 1.3.5-release or the next 1.3.6-release

![image](https://user-images.githubusercontent.com/4902714/113411798-450bdb00-93e9-11eb-9533-0b783dd5aa7c.png)

**Comment by chengshiwen** [comment] 2021-04-10 09:02
Close this issue since it can't be reproduced

**Closed by chengshiwen** 2021-04-10 09:02 UTC
Labels: improvement
