### ISSUE TITLE
[Improvement][ui] Change the no to taskinstance, processinstance, processdefinition id

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#3725] opened 2020-09-12 02:38 UTC
**Describe the question**
Change the no to taskinstance, processinstance, processdefinition id

**What are the current deficiencies and the benefits of improvement**
- It can help user to locate the params of taskinstance, processinstance, processdefinition faster.

**Which version of DolphinScheduler:**
 -[dev]

**Describe alternatives you've considered**
![image](https://user-images.githubusercontent.com/29545877/92985325-15949000-f4e4-11ea-878b-dbd8cf81ded7.png)

**Comment by zhuangchong** [comment] 2020-09-15 01:49
+1

**Comment by yangyichao-mango** [comment] 2020-09-16 05:00
Easy to implement， anyone who are interested in this feature, welcome to leave a message.

**Comment by shiyi23** [comment] 2020-12-15 09:28
hello, I am interested in this feature, and I want to contribute, can you assign it to me?

**Comment by CalvinKirs** [comment] 2020-12-15 09:34
> hello, I am interested in this feature, and I want to contribute, can you assign it to me?

Very welcome, if you encounter any problems, you can also communicate with me

**Comment by shiyi23** [comment] 2020-12-15 09:41
> > hello, I am interested in this feature, and I want to contribute, can you assign it to me?
> 
> Very welcome, if you encounter any problems, you can also communicate with me

Do I need to write any code?

**Comment by CalvinKirs** [comment] 2020-12-15 09:43
> > > hello, I am interested in this feature, and I want to contribute, can you assign it to me?
> > 
> > 
> > Very welcome, if you encounter any problems, you can also communicate with me
> 
> Do I need to write any code?

Do you understand this question?

**Comment by shiyi23** [comment] 2020-12-15 09:53
> > > > hello, I am interested in this feature, and I want to contribute, can you assign it to me?
> > > 
> > > 
> > > Very welcome, if you encounter any problems, you can also communicate with me
> > 
> > 
> > Do I need to write any code?
> 
> Do you understand this question?

well, my mistake...It seems that I can not address the issue, please forgive me😥😥you can assign this issue to others.

**Comment by CalvinKirs** [comment] 2020-12-15 09:58
> > > > > hello, I am interested in this feature, and I want to contribute, can you assign it to me?
> > > > 
> > > > 
> > > > Very welcome, if you encounter any problems, you can also communicate with me
> > > 
> > > 
> > > Do I need to write any code?
> > 
> > 
> > Do you understand this question?
> 
> well, my mistake...It seems that I can not address the issue, please forgive me😥😥you can assign this issue to others.

ok,If there is a chance in the future, I look forward to your contribution.

**Comment by shiyi23** [comment] 2020-12-15 09:59
> > > > > > hello, I am interested in this feature, and I want to contribute, can you assign it to me?
> > > > > 
> > > > > 
> > > > > Very welcome, if you encounter any problems, you can also communicate with me
> > > > 
> > > > 
> > > > Do I need to write any code?
> > > 
> > > 
> > > Do you understand this question?
> > 
> > 
> > well, my mistake...It seems that I can not address the issue, please forgive me😥😥you can assign this issue to others.
> 
> ok,If there is a chance in the future, I look forward to your contribution.

Thanks your encouragement！

**Comment by kalencaya** [comment] 2020-12-24 12:48
hi, can assign it to me? I'm using dolphinscheduler and want to contribute.

**Comment by CalvinKirs** [comment] 2020-12-24 14:17
> hi, can assign it to me? I'm using dolphinscheduler and want to contribute.

Very welcome, if you encounter any problems, you can also communicate with me

**Comment by kalencaya** [comment] 2020-12-29 11:33
I'm confused what the issue means.
I just change the auto-generated number beside the checkbox to the  askinstance、processinstance、processdefinition id, but refused by pr reviewer.
can point out what ui style this issue want to achive? 
the follow image provided by pr reviewer.
![103192441-a2d4e680-4913-11eb-8c2d-2f3437d56239](https://user-images.githubusercontent.com/24804318/103280993-adbf7200-4a0c-11eb-80a5-ac50aee3af59.png)

**Comment by dailidong** [comment] 2021-01-30 14:57
> I'm confused what the issue means.
> I just change the auto-generated number beside the checkbox to the taskinstance、processinstance、processdefinition id, but refused by pr reviewer.
> can point out what ui style this issue want to achive?
> the follow image provided by pr reviewer, it is also what i fixed.
> ![103192441-a2d4e680-4913-11eb-8c2d-2f3437d56239](https://user-images.githubusercontent.com/24804318/103280993-adbf7200-4a0c-11eb-80a5-ac50aee3af59.png)

sorry for reply late, I re-check this issue, I think the issue is right, I will talk about the PR reviewer

**Closed** 2021-02-05 03:28 UTC
Labels: UI, easy to fix
