### ISSUE TITLE
[Bug][UI] if the program type I choose is Python, it should be choose python file, not jar package

### ISSUE THREAD

**Issue by ccckoyn** [apache/incubator-dolphinscheduler#3926] opened 2020-10-16 07:22 UTC
*For better global communication, please give priority to using English description, thx! *

*Please review https://dolphinscheduler.apache.org/en-us/docs/development/issue.html when describe an issue.*

**Describe the bug**
When configuring spark nodes, if the program type I choose is Python, it should be choose python file, not jar package
**To Reproduce**
Steps to reproduce the behavior, for example:
configure spark node

**Expected behavior**
it should be choose python file, not jar pakage

**Screenshots**

**Which version of Dolphin Scheduler:**
 -[1.3.1-preview]

**Additional context**

**Requirement or improvement**
- Please describe about your requirements or improvement suggestions.

**Comment by ccckoyn** [comment] 2020-10-16 07:23
Screenshots
![image](https://user-images.githubusercontent.com/25679544/96225306-7c193c00-0fc3-11eb-86ed-490c97b51043.png)

**Comment by break60** [comment] 2020-10-16 08:05
1.3.2 There is a fix for this problem

**Comment by xingchun-chen** [comment] 2020-10-21 02:16
the issue is the same as #3469 ,Fixed in version 1.3.2

**Closed by xingchun-chen** 2020-10-21 02:16 UTC
Labels: bug
