### ISSUE TITLE
ambari plugin（ambari插件）

### ISSUE THREAD

**Issue by boandai** [apache/incubator-dolphinscheduler#250] opened 2019-05-06 13:47 UTC

**Comment by dailidong** [comment] 2019-12-17 13:09
Duplicate of #1469

**Closed by dailidong** 2019-12-17 13:09 UTC
Labels: new feature

**Comment by gaojun2048** [comment] 2020-02-17 02:28
@dailidong  
After the development of the ambari plugin is complete, we need a file server to place the dolphinscheduler rpm packages. Users of the dolphinscheduler can add the dolphinscheduler rpm package to their own yum repo, and then can use the ambari plugin to install the dolphinscheduler.
