### ISSUE TITLE
How to keep only one instance running at the same time

### ISSUE THREAD

**Issue by cconlyou** [apache/incubator-dolphinscheduler#1995] opened 2020-02-21 14:36 UTC
If we have some processes do not support parallel execution. 
How to keep only one instance running at the same time ?

example 1 :
One instance is running by schedule service . If we start another instance by hand, how to keep these instances run by order.

example 2 :
If the schedule's interval is short, such as per minute, and the duration of each instance is not regular. We want the next instance to wait until previous instance run end.

**Comment by cconlyou** [comment] 2020-02-27 03:12
Can anyone help me ?

**Comment by dailidong** [comment] 2020-04-22 13:53
Duplicate of #1211,  the comments should also see

**Comment by dailidong** [comment] 2020-04-22 13:57
if you have some comments, please comment on the #1211,  I will close this issue

**Closed by dailidong** 2020-04-22 13:57 UTC
Labels: enhancement, question
