### ISSUE TITLE
File upload failed

### ISSUE THREAD

**Issue by pptfz** [apache/incubator-dolphinscheduler#4607] opened 2021-01-28 09:35 UTC
```
File upload error 413, I am the docker installation, nginx has configured the upload limit in the size, in dolphinscheduler dolphinscheduler configuration file/dolphinscheduler - API/SRC/main/resources/application - API. The properties of modified the following two, or not
spring.servlet.multipart.max-file-size=10240MB
spring.servlet.multipart.max-request-size=10240MB
```

![image](https://user-images.githubusercontent.com/44946546/106118056-a5cf2b00-618e-11eb-8121-b355f6975353.png)

**Comment by dailidong** [comment] 2021-01-29 10:02
Duplicate of https://github.com/apache/incubator-dolphinscheduler/issues/3795

**Comment by dailidong** [comment] 2021-01-29 10:03
> Duplicate of #3795
I will close this issue , if you not solved, you can reopen it

**Closed by dailidong** 2021-01-29 10:03 UTC
Labels: question
