### ISSUE TITLE
why my process_instance is allways starting....(为什么我的工作流实例一直显示正在运行)

### ISSUE THREAD

**Issue by JohnBarrowman65** [apache/incubator-dolphinscheduler#2427] opened 2020-04-15 02:25 UTC
[1.1.0-release]
--1.2.0版本
my system is ubuntu
--电脑是ubuntu系统
**Describe the question**
after run my project , i at the instance of quick-start to create a task (just echo 123)，bug the process_instance is allways starting,and the log is show 'task instance not found'.the projecess is always debuuger imeeages: consume tasks: [],there still have 1 tasks need to be executed
--问题是这样的，项目跑起来后，根据快速使用介绍，新建了一个工作流程，保存上线后点击了运行，来到实例那边，实例一直显示正在执行，我的任务是简单的打印一个echo 123。然后点击日志报错task instance not found'，后台项目一直debugger信息提示的是consume tasks: [],there still have 1 tasks need to be executed
![image](https://user-images.githubusercontent.com/30208746/79292313-5d969300-7f03-11ea-98e0-e38c90beed5b.png)
![image](https://user-images.githubusercontent.com/30208746/79292345-6ab38200-7f03-11ea-8902-dbf58abbbd12.png)
![image](https://user-images.githubusercontent.com/30208746/79292534-ef060500-7f03-11ea-95c7-f95a06373060.png)

**Comment by JohnBarrowman65** [comment] 2020-04-15 02:28
![image](https://user-images.githubusercontent.com/30208746/79292518-e1507f80-7f03-11ea-9d6f-44f82184c3b5.png)

**Comment by JohnBarrowman65** [comment] 2020-04-15 02:58
help the childs
--救救孩子吧

**Comment by dailidong** [comment] 2020-04-15 04:14
have  you done some operations?  like delete opertation

**Comment by JohnBarrowman65** [comment] 2020-04-15 06:23
> have you done some operations? like delete opertation

no, i reinstall the zookeeper.and now when i see the log is this
![image](https://user-images.githubusercontent.com/30208746/79304672-76fc0700-7f24-11ea-98cb-4fa7970e0c45.png)
the process_instance is still staring... and the log from web ui is notting
![image](https://user-images.githubusercontent.com/30208746/79304755-a0b52e00-7f24-11ea-9780-dfd7a753199a.png)

**Comment by huiyuanlu** [comment] 2020-04-15 08:33
Its looks like zookeeper and master/work server is OK. Maybe, you need grant login user to tenant. The tenant is real user.

**Comment by JohnBarrowman65** [comment] 2020-04-15 11:11
> Its looks like zookeeper and master/work server is OK. Maybe, you need grant login user to tenant. The tenant is real user.

thinks replays first, i had login with the tenant,and i can found the sh files in my disk
![image](https://user-images.githubusercontent.com/30208746/79330777-ac1c4f80-7f4c-11ea-80ab-599990741a53.png)
but as you can see the process is still here always,i can't do the next step

**Comment by xingchun-chen** [comment] 2020-04-16 01:52
you can delete the data of zk queue then restart the service，can the problem be reproduced

**Comment by JohnBarrowman65** [comment] 2020-04-16 04:03
> you can delete the data of zk queue then restart the service，can the problem be reproduced
thinks , i can work now,but the reasean is my user opertation sudo doesn't remove the passwd.

**Comment by xingchun-chen** [comment] 2020-04-16 05:41
if your issue is solved, please close it

**Closed** 2020-04-16 06:13 UTC
Labels: question
