### ISSUE TITLE
Concurrent task log bug

### ISSUE THREAD

**Issue by 865357384** [apache/incubator-dolphinscheduler#730] opened 2019-08-23 01:59 UTC
Describe the bug：
When the concurrent task runs, the log interleaving error occurs and the log is written.

Case：
![image](https://user-images.githubusercontent.com/24928399/63561368-4bd73880-c58c-11e9-81ec-b83bba13a60b.png)
![image](https://user-images.githubusercontent.com/24928399/63561413-69a49d80-c58c-11e9-8d10-23797953e070.png)
![image](https://user-images.githubusercontent.com/24928399/63561420-6f01e800-c58c-11e9-8f13-da82a1638c16.png)

Which version of Easy Scheduler:
-[1.1.0]

**Comment by dailidong** [comment] 2019-08-24 07:08
Duplicate of #627

**Comment by qiaozhanwei** [comment] 2019-08-29 03:45
1, the log error has been resolved in 1.1.0, but it is filtered on the server side of gRPC
Not filtered from the thread that intercepts the log from the logback, that is, the bottom of the logback
The log intercepted by Linux is still garbled
2, you can verify by the following steps
1) Find the log all in the path
For example, the log is stored in /data1/escheduler/logs/65/5012/85119.log
2) LoggerServer gRPC IP and port access
LogClient logClient = new LogClient(host, Constants.RPC_PORT);
String log = logClient.rollViewLog(taskInstance.getLogPath(),skipLineNum,limit);

Note: Make sure it is version 1.1.0

1，日志错误在1.1.0中已经解决了，不过是在gRPC的服务端过滤的
不是从logback 拦截日志的线程中过滤的，也就是说，logback底层
Linux 拦截的日志还是错乱的
2，可以通过以下步骤进行验证
1) 找到日志所有在路径
比如说，日志存放在 /data1/escheduler/logs/65/5012/85119.log
2) LoggerServer gRPC IP 和 端口 进行访问
LogClient logClient = new LogClient(host, Constants.RPC_PORT);
String log = logClient.rollViewLog(taskInstance.getLogPath(),skipLineNum,limit);

注意：确保是1.1.0版本

**Closed** 2019-09-26 10:01 UTC
Labels: bug
