### ISSUE TITLE
[BUG] NEF when get info from OSUtils

### ISSUE THREAD

**Issue by yangyichao-mango** [apache/incubator-dolphinscheduler#2927] opened 2020-06-08 11:01 UTC
**Describe the bug**
`OSUtils.cpuUsage()` function will produce NumberFormatException if cpuUsage() function returns `0.0 / 0.0 = NaN`.

**To Reproduce**
When I start my WorkerServer in my MacOS, it will schedule to produce a heartbeat signal to zk, and it will produce NFE when get `cpuUsage()` result equals `NaN`(0.0 / 0.0) from `oshi.AbstractCentralProcessor#getSystemCpuLoad()`.

**Screenshots**
![image](https://user-images.githubusercontent.com/29545877/84022235-8180cd00-a9b8-11ea-8f9b-f4b593c69f05.png)

**Which version of Dolphin Scheduler:**
 -[dev]

**Requirement or improvement
- Use `Double#isNaN()` to judge the result although it returns double type, it will not throw NFE when the result is NaN(0.0 / 0.0).
- Judge every place that use the double type in OSUtils and add `Double#isNaN()` judgement.
![image](https://user-images.githubusercontent.com/29545877/84023209-42ec1200-a9ba-11ea-9f6b-756486f724cc.png)

**Comment by gabrywu** [comment] 2020-06-11 12:57
can't see your uploaded image

**Comment by gabrywu** [comment] 2020-06-11 13:02
can't reproduce the NPE in my MAC laptop

**Comment by yangyichao-mango** [comment] 2020-06-11 13:02
> can't see your uploaded image

There are the images.

https://user-images.githubusercontent.com/29545877/84023209-42ec1200-a9ba-11ea-9f6b-756486f724cc.png

https://user-images.githubusercontent.com/29545877/84022235-8180cd00-a9b8-11ea-8f9b-f4b593c69f05.png

**Comment by yangyichao-mango** [comment] 2020-06-11 13:03
> can't reproduce the NPE in my MAC laptop

This mistake can't be repeated every time. It happens occasionally.

**Comment by gabrywu** [comment] 2020-06-11 13:23
bug accordin to the API doc of getSystemCpuLoad, it will return [0.0,1.0], how can it return Nan?

**Comment by yangyichao-mango** [comment] 2020-06-11 13:34
> but accordin to the API doc of getSystemCpuLoad, it will return [0.0,1.0], how can it return Nan?

Can you paste the API doc of getSystemCpuLoad, I do not find the description about [0.0,1.0] when I check the source code java doc. But it actually returns NaN in my laptop. So I think there are two things need to do.

1.Find why it returns NaN. And I found the issue https://github.com/naver/pinpoint/issues/914, and it use the same `OperatingSystemMXBean.getSystemCpuLoad()`, and also returns NaN.
2.I think whatever the reason is, it's better to add Double.isNaN check.

**Comment by gabrywu** [comment] 2020-06-12 02:18
/**
     * Returns the "recent cpu usage" for the whole system from
     * {@link com.sun.management.OperatingSystemMXBean#getSystemCpuLoad()} if a
     * user is running the Oracle JVM. This value is a double in the [0.0,1.0]
     * interval. A value of 0.0 means that all CPUs were idle during the recent
     * period of time observed, while a value of 1.0 means that all CPUs were
     * actively running 100% of the time during the recent period being
     * observed. All values between 0.0 and 1.0 are possible depending of the
     * activities going on in the system. If the system recent cpu usage is not
     * available, the method returns a negative value. Calling this method
     * immediately upon instantiating the {@link CentralProcessor} may give
     * unreliable results. If a user is not running the Oracle JVM, this method
     * will default to the behavior and return value of
     * {@link #getSystemCpuLoadBetweenTicks()}.
     *
     * @return the "recent cpu usage" for the whole system; a negative value if
     *         not available.
     */
    @SuppressWarnings("restriction")

**Comment by gabrywu** [comment] 2020-06-12 02:21
> > but accordin to the API doc of getSystemCpuLoad, it will return [0.0,1.0], how can it return Nan?
> 
> Can you paste the API doc of getSystemCpuLoad, I do not find the description about [0.0,1.0] when I check the source code java doc. But it actually returns NaN in my laptop. I think maybe this exception occurs depending on different laptop hardware environments. So I think there are two things need to do.
> 
> 1.Find why it returns NaN. And I found the issue [naver/pinpoint#914](https://github.com/naver/pinpoint/issues/914), and it use the same `OperatingSystemMXBean.getSystemCpuLoad()`, and also returns NaN.
> 2.I think whatever the reason is, it's better to add Double.isNaN check.

OK, good suggestions. do you mind to create a PR to resolve this ?

**Comment by yangyichao-mango** [comment] 2020-06-12 02:27
> > > but accordin to the API doc of getSystemCpuLoad, it will return [0.0,1.0], how can it return Nan?
> 
> > 
> 
> > Can you paste the API doc of getSystemCpuLoad, I do not find the description about [0.0,1.0] when I check the source code java doc. But it actually returns NaN in my laptop. I think maybe this exception occurs depending on different laptop hardware environments. So I think there are two things need to do.
> 
> > 
> 
> > 1.Find why it returns NaN. And I found the issue [naver/pinpoint#914](https://github.com/naver/pinpoint/issues/914), and it use the same `OperatingSystemMXBean.getSystemCpuLoad()`, and also returns NaN.
> 
> > 2.I think whatever the reason is, it's better to add Double.isNaN check.
> 
> 
> 
> OK, good suggestions. do you mind to create a PR to resolve this ? 

I will do it.

**Comment by gabrywu** [comment] 2020-06-12 03:12
> > > > but accordin to the API doc of getSystemCpuLoad, it will return [0.0,1.0], how can it return Nan?
> > 
> > 
> > > 
> > 
> > 
> > > Can you paste the API doc of getSystemCpuLoad, I do not find the description about [0.0,1.0] when I check the source code java doc. But it actually returns NaN in my laptop. I think maybe this exception occurs depending on different laptop hardware environments. So I think there are two things need to do.
> > 
> > 
> > > 
> > 
> > 
> > > 1.Find why it returns NaN. And I found the issue [naver/pinpoint#914](https://github.com/naver/pinpoint/issues/914), and it use the same `OperatingSystemMXBean.getSystemCpuLoad()`, and also returns NaN.
> > 
> > 
> > > 2.I think whatever the reason is, it's better to add Double.isNaN check.
> > 
> > 
> > OK, good suggestions. do you mind to create a PR to resolve this ?
> 
> I will do it.

Thanks a lot ,when you finish it ,you can @ me to review . I will close this  issue , feel free to re-poen it if you think it's necessary

**Closed by gabrywu** 2020-06-12 03:12 UTC
Labels: bug
