### ISSUE TITLE
UDF函数功能无法使用

### ISSUE THREAD

**Issue by 13521460205** [apache/incubator-dolphinscheduler#2435] opened 2020-04-15 11:14 UTC
1，创建通过hive数据源，查询数据时，选择UDF函数，确认添加以后，重新进入编辑状态，udf函数并没有保存上，
2，请问创建udf函数后，是否会将函数“临时”或“永久”增加到hive函数库中吗？

**Comment by dailidong** [comment] 2020-04-15 11:55
please update/add title/desc in English, thx

**Comment by 13521460205** [comment] 2020-04-16 01:24
the version is 1.20

question:

1. Select UDF function, confirm to add, and enter editing state again. UDF function is not saved,

2. Will UDF function be added to hive function library "temporarily" or "permanently" after it is created?

**Comment by 13521460205** [comment] 2020-04-16 01:30
![Uploading image.png…]()

**Comment by xingchun-chen** [comment] 2020-04-16 01:59
1.the issue is resoved ,do you compile the source code or download the compressed package

**Comment by xingchun-chen** [comment] 2020-04-16 01:59
Not saved successfully, will not increase to hive function library

**Comment by 13521460205** [comment] 2020-04-16 02:05
I use the download package. Do I need to download the source code to compile the latest package? Or download the latest installation package again?

**Comment by 13521460205** [comment] 2020-04-16 05:43
I downloaded the latest back package and replaced all the jar packages under lib / and the problem still hasn't been solved after restarting the service

**Comment by xingchun-chen** [comment] 2020-04-16 05:47
This problem is caused by the front-end code, you can download the front-end code again and try again

**Comment by 13521460205** [comment] 2020-04-16 06:09
I updated the front-end package and restarted nginx. The problem still exists

**Comment by break60** [comment] 2020-04-16 06:55
The front-end source code plus this code or upgrade to 1.2.1

**Comment by 13521460205** [comment] 2020-04-16 09:13
Can you send me the JS file that needs to be replaced, because I haven't edited the previous source environment here, thank you

**Comment by break60** [comment] 2020-04-16 09:17
https://github.com/apache/incubator-dolphinscheduler/blob/1.2.0-release/dolphinscheduler-ui/src/js/conf/home/pages/dag/_source/formModel/tasks/_source/udfs.vue

Download it yourself and change it

**Comment by 13521460205** [comment] 2020-04-16 11:05
I modified the front-end source code, packed and replaced the dist directory. The problem still exists

**Comment by break60** [comment] 2020-04-17 01:59
> I modified the front-end source code, packed and replaced the dist directory. The problem still exists

udfs page also needs to delete an id

**Comment by xingchun-chen** [comment] 2020-04-24 03:00
if the issue is solved,please close it

**Comment by 13521460205** [comment] 2020-04-24 03:50
Problem solved，thanks

**Closed** 2020-04-24 03:49 UTC
Labels: bug
