### ISSUE TITLE
 The log information is suggested to be omitted. . .（log信息建议省略一下。。。）

### ISSUE THREAD

**Issue by ronyang1985** [apache/incubator-dolphinscheduler#455] opened 2019-06-13 12:49 UTC
https://github.com/analysys/EasyScheduler/blob/8eefa0e947ad8052485901801665833dabe17de0/escheduler-server/src/main/java/cn/escheduler/server/worker/task/sql/SqlTask.java#L281

**Comment by lidongdai** [comment] 2019-06-13 14:19
good idea, thx!

and if don't want to see too many log info , can set log level to warn or error !

**Comment by dailidong** [comment] 2020-12-16 03:26
Duplicate of https://github.com/apache/incubator-dolphinscheduler/issues/226

**Closed by dailidong** 2020-12-16 03:26 UTC
Labels: enhancement
